services:
  - type: web
    name: fitnesstracker-backend
    env: node
    buildCommand: npm install
    startCommand: npm run dev
    rootDir: server
    envVars:
      - key: JWT_SECRET
        value: mysecretkey123
 